/**
 * 快速體驗 - 創建案件頁面（極致美學版）
 */

import { useState, useEffect, useRef } from 'react';
import { useMountedRef } from '@/hooks/useMountedRef';
import { useNavigate } from 'react-router-dom';
import { logger } from '@/utils/logger';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Alert,
  Button,
  Progress,
  Typography,
  message,
} from 'antd';
import { useSessionStore } from '@/store/sessionStore';
import { useCaseStore } from '@/store/caseStore';
import { validateStatement } from '@/utils/validate';
import { MAX_IMAGE_COUNT, MIN_DEFENDANT_LENGTH } from '@/utils/constants';
import { localStore, sessionStorage, caseSessionMap } from '@/utils/storage';
import StatementInput from '@/components/business/StatementInput';
import FileUpload from '@/components/business/FileUpload';
import type { UploadFile } from 'antd/es/upload/interface';
import SEO from '@/components/common/SEO';
import { getErrorMessage } from '@/utils/apiError';
import { t } from '@/utils/i18n';
import './Create.less';

const { Title, Text } = Typography;
const DRAFT_STORAGE_KEY = 'quick_case_draft';

interface CaseDraft {
  plaintiffStatement: string;
  defendantStatement: string;
  evidenceUrls: string[];
}

const QuickExperienceCreate = () => {
  const navigate = useNavigate();
  const { session, createSession, setSession } = useSessionStore();
  const { createQuickCase, isLoading } = useCaseStore();

  const [currentStep, setCurrentStep] = useState(0);
  const [plaintiffStatement, setPlaintiffStatement] = useState('');
  const [defendantStatement, setDefendantStatement] = useState('');
  const [evidenceFiles, setEvidenceFiles] = useState<UploadFile[]>([]);
  const [isGeneratingDefendant, setIsGeneratingDefendant] = useState(false);
  const [autoSaveStatus, setAutoSaveStatus] = useState<'saved' | 'saving' | null>(null);
  const [recoveredCase, setRecoveredCase] = useState<{ id: string; status: string } | null>(null);
  const [sessionInitError, setSessionInitError] = useState<string | null>(null);
  const [isRetryingSession, setIsRetryingSession] = useState(false);
  
  const submitLockRef = useRef(false);
  const mountedRef = useMountedRef();
  const autoGenTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const ensureSession = async (isManualRetry = false) => {
    if (isManualRetry && mountedRef.current) {
      setIsRetryingSession(true);
    }

    try {
      await createSession();
      if (mountedRef.current) {
        setSessionInitError(null);
      }
    } catch (error) {
      logger.warn('Failed to create session', error);
      if (mountedRef.current) {
        setSessionInitError(t('quickCreate.sessionInitWeakWarning'));
      }
    } finally {
      if (isManualRetry && mountedRef.current) {
        setIsRetryingSession(false);
      }
    }
  };

  useEffect(() => {
    const existingSessionId = sessionStorage.get() || session?.session_id;
    if (!existingSessionId) {
      createSession()
        .then(() => {
          if (mountedRef.current) {
            setSessionInitError(null);
          }
        })
        .catch((error: unknown) => {
          logger.warn('Failed to create session', error);
          if (mountedRef.current) {
            setSessionInitError(t('quickCreate.sessionInitWeakWarning'));
          }
        });
    }
  }, [session, createSession, mountedRef]);

  // 檢查是否有未完成的案件（僅在 session_id 存在且變更時呼叫一次，避免重複 404）
  const sessionId = session?.session_id ?? sessionStorage.get();
  useEffect(() => {
    if (!sessionId) return;
    const checkRecoveredCase = async () => {
      try {
        const { getCaseBySessionId } = await import('@/services/api/case');
        const existingCase = await getCaseBySessionId(sessionId);
        if (existingCase && existingCase.status === 'draft' && mountedRef.current) {
          setRecoveredCase({ id: existingCase.id, status: existingCase.status });
        }
      } catch (error) {
        logger.warn('Failed to check recovered case', error);
      }
    };
    checkRecoveredCase();
  }, [sessionId]);

  // 載入草稿
  useEffect(() => {
    const draft = localStore.get<CaseDraft>(DRAFT_STORAGE_KEY);
    if (draft) {
      setPlaintiffStatement(draft.plaintiffStatement || '');
      setDefendantStatement(draft.defendantStatement || '');
    }
  }, []);

  // 自動保存草稿
  useEffect(() => {
    if (!plaintiffStatement && !defendantStatement) return;
    
    setAutoSaveStatus('saving');
    const timer = setTimeout(() => {
      localStore.set(DRAFT_STORAGE_KEY, {
        plaintiffStatement,
        defendantStatement,
        evidenceUrls: [],
      });
      if (mountedRef.current) {
        setAutoSaveStatus('saved');
        setTimeout(() => {
          if (mountedRef.current) setAutoSaveStatus(null);
        }, 2000);
      }
    }, 1000);

    return () => clearTimeout(timer);
  }, [plaintiffStatement, defendantStatement, mountedRef]);

  const canSubmit = validateStatement(plaintiffStatement).valid;

  const handleAutoGenerateDefendant = () => {
    if (!plaintiffStatement.trim()) {
      message.info(t('message.fillPlaintiffFirst'));
      return;
    }
    setIsGeneratingDefendant(true);
    const source = plaintiffStatement.slice(0, 120);
    const draft = t('quickCreate.defendantDraftTemplate').replace('{source}', source);
    if (autoGenTimeoutRef.current) {
      clearTimeout(autoGenTimeoutRef.current);
    }
    autoGenTimeoutRef.current = setTimeout(() => {
      if (!mountedRef.current) return;
      setDefendantStatement(draft);
      setIsGeneratingDefendant(false);
      message.success(t('message.defendantDraftDone'));
    }, 600);
  };

  useEffect(() => {
    return () => {
      if (autoGenTimeoutRef.current) {
        clearTimeout(autoGenTimeoutRef.current);
      }
    };
  }, []);

  const handleSubmit = async () => {
    if (submitLockRef.current) return;
    if (!canSubmit) {
      message.warning(t('message.completePlaintiff'));
      return;
    }

    submitLockRef.current = true;
    try {
      if (!sessionStorage.get() && !session?.session_id) {
        await ensureSession();
      }

      const result = await createQuickCase({
        plaintiff_statement: plaintiffStatement.trim(),
        defendant_statement: defendantStatement.trim() || '',
        evidence_urls: [],
      });

      if (!result?.case?.id) {
        throw new Error(t('message.submitFail'));
      }

      if (result.session_id) {
        sessionStorage.set(result.session_id);
        caseSessionMap.set(result.case.id, result.session_id);
        if (result.session_expires_at) {
          setSession({ session_id: result.session_id, expires_at: result.session_expires_at });
        }
      }

      const filesToUpload = evidenceFiles
        .filter((f): f is UploadFile & { originFileObj: File } => Boolean(f?.originFileObj))
        .map((f) => f.originFileObj);

      if (filesToUpload.length > 0) {
        try {
          const { uploadEvidence } = await import('@/services/api/case');
          const sessionIdToUse = result.session_id || sessionStorage.get() || session?.session_id;
          if (sessionIdToUse) {
            await uploadEvidence(result.case.id, filesToUpload as File[], sessionIdToUse);
          }
        } catch {
          try { localStorage.setItem(`pending_evidence_${result.case.id}`, 'true'); } catch { /* noop */ }
        }
      }

      localStore.remove(DRAFT_STORAGE_KEY);
      if (mountedRef.current) navigate(`/quick-experience/result/${result.case.id}`);
    } catch (error: unknown) {
      if (mountedRef.current) message.error(getErrorMessage(error, 'message.submitFail'));
    } finally {
      submitLockRef.current = false;
    }
  };

  const handleNextStep = () => {
    if (currentStep === 0 && !canSubmit) {
      message.warning(t('message.completePlaintiff'));
      return;
    }
    setCurrentStep(prev => Math.min(prev + 1, 2));
  };

  const handlePrevStep = () => {
    setCurrentStep(prev => Math.max(prev - 1, 0));
  };

  return (
    <>
      <SEO title={t('quickCreate.title')} description={t('quickCreate.description')} keywords={t('quickCreate.keywords')} />
      
      <div className="quick-experience-create typeform-style">
        <div className="typeform-header">
          <Button type="text" onClick={() => navigate('/')} className="back-btn">
            {t('quickCreate.close')}
          </Button>
          <div className="flex items-center gap-4">
            {autoSaveStatus === 'saving' && <Text type="secondary" className="text-sm">{t('quickCreate.autoSaving')}</Text>}
            {autoSaveStatus === 'saved' && <Text type="success" className="text-sm">{t('quickCreate.autoSaved')}</Text>}
            <Progress percent={((currentStep + 1) / 3) * 100} showInfo={false} strokeColor="#84A59D" className="step-progress" />
          </div>
        </div>

        {recoveredCase && (
          <div className="fixed top-20 left-1/2 -translate-x-1/2 z-50 w-full max-w-md px-4">
            <div className="bg-blue-50 border border-blue-200 rounded-2xl p-4 shadow-lg flex items-center justify-between">
              <Text className="text-blue-800">{t('quickCreate.recoveredCase.title')}</Text>
              <Button type="primary" size="small" shape="round" onClick={() => navigate(`/quick-experience/result/${recoveredCase.id}`)}>
                {t('quickCreate.recoveredCase.continue')}
              </Button>
            </div>
          </div>
        )}

        {sessionInitError && (
          <div className="mx-auto mb-6 w-full max-w-3xl px-4">
            <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 shadow-sm">
              <Alert
                type="warning"
                showIcon
                className="mb-3"
                title={sessionInitError}
              />
              <div className="flex items-center justify-between gap-4">
                <Text type="secondary">{t('quickCreate.sessionInitWeakHint')}</Text>
                <Button onClick={() => void ensureSession(true)} loading={isRetryingSession}>
                  {t('quickCreate.sessionInitRetry')}
                </Button>
              </div>
            </div>
          </div>
        )}

        <AnimatePresence mode="wait">
          {currentStep === 0 && (
            <motion.div 
              key="step0"
              className="typeform-step"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.5 }}
            >
              <div className="step-content">
                <Title level={2} className="step-title">{t('quickCreate.step1.title')}</Title>
                <Text className="step-subtitle text-lg text-gray-500 mb-8 block">
                  {t('quickCreate.step1.subtitle')}
                </Text>
                
                <StatementInput
                  value={plaintiffStatement}
                  onChange={setPlaintiffStatement}
                  role="plaintiff"
                  showGuide={true}
                  minLength={30}
                />
                
                <div className="step-actions mt-8">
                  <Button 
                    type="primary" 
                    size="large" 
                    className="next-btn h-14 px-12 text-lg rounded-full"
                    onClick={handleNextStep}
                    disabled={!canSubmit}
                  >
                    {t('quickCreate.step.next')}
                  </Button>
                  <Text className="hint-text ml-4 text-gray-400">{t('quickCreate.step.enterHint')}</Text>
                </div>
              </div>
            </motion.div>
          )}

          {currentStep === 1 && (
            <motion.div 
              key="step1"
              className="typeform-step"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.5 }}
            >
              <div className="step-content">
                <Alert
                  type="info"
                  showIcon
                  className="step2-handoff-alert mb-8"
                  title={t('quickCreate.step2.handoffPrompt')}
                />
                <Title level={2} className="step-title">{t('quickCreate.step2.title')}</Title>
                <Text className="step-subtitle text-lg text-gray-500 mb-8 block">
                  {t('quickCreate.step2.subtitle')}
                </Text>
                
                <StatementInput
                  value={defendantStatement}
                  onChange={setDefendantStatement}
                  role="defendant"
                  showGuide={true}
                  allowEmpty
                  minLength={MIN_DEFENDANT_LENGTH}
                />
                
                <div className="step-actions mt-8 flex items-center gap-4">
                  <Button 
                    size="large" 
                    className="prev-btn h-14 px-8 text-lg rounded-full"
                    onClick={handlePrevStep}
                  >
                    {t('quickCreate.step.prev')}
                  </Button>
                  <Button 
                    type="primary" 
                    size="large" 
                    className="next-btn h-14 px-12 text-lg rounded-full"
                    onClick={handleNextStep}
                  >
                    {t('quickCreate.step.next')}
                  </Button>
                  <Button type="link" loading={isGeneratingDefendant} onClick={handleAutoGenerateDefendant} className="text-primary">
                    {t('quickCreate.autoWrite')}
                  </Button>
                </div>
              </div>
            </motion.div>
          )}

          {currentStep === 2 && (
            <motion.div 
              key="step2"
              className="typeform-step"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.5 }}
            >
              <div className="step-content">
                <Title level={2} className="step-title">{t('quickCreate.step3.title')}</Title>
                <Text className="step-subtitle text-lg text-gray-500 mb-8 block">
                  {t('quickCreate.step3.subtitle')}
                </Text>
                
                <div className="evidence-upload-wrapper bg-white p-8 rounded-3xl shadow-sm border border-gray-100">
                  <FileUpload value={evidenceFiles} onChange={setEvidenceFiles} maxCount={MAX_IMAGE_COUNT} />
                </div>
                
                <div className="step-actions mt-12 flex items-center gap-4">
                  <Button 
                    size="large" 
                    className="prev-btn h-14 px-8 text-lg rounded-full"
                    onClick={handlePrevStep}
                  >
                    {t('quickCreate.step.prev')}
                  </Button>
                  <Button 
                    type="primary" 
                    size="large" 
                    className="submit-btn h-14 px-12 text-lg rounded-full shadow-lg hover:shadow-xl transition-all"
                    onClick={handleSubmit}
                    loading={isLoading}
                  >
                    {isLoading ? t('quickCreate.submitting') : t('quickCreate.submitAndAnalyze')}
                  </Button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </>
  );
};

export default QuickExperienceCreate;
