/**
 * 快速體驗 - 創建案件頁面
 *
 * 遷移: Ant Design Button/Typography/Progress/Alert/message → shadcn/ui + Tailwind + sonner
 * 保留: StatementInput, FileUpload（業務組件仍用 Ant Design，後續單獨遷移）
 * 保留: 所有業務邏輯（session, draft, auto-save, submit, evidence upload）
 */

import { useState, useEffect, useRef } from 'react';
import { useMountedRef } from '@/hooks/useMountedRef';
import { useNavigate } from 'react-router-dom';
import { logger } from '@/utils/logger';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'sonner';
import { X, AlertTriangle, Info, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { useSessionStore } from '@/store/sessionStore';
import { useCaseStore } from '@/store/caseStore';
import { validateStatement } from '@/utils/validate';
import { MAX_IMAGE_COUNT, MIN_DEFENDANT_LENGTH } from '@/utils/constants';
import { localStore, sessionStorage, caseSessionMap } from '@/utils/storage';
import StatementInput from '@/components/business/StatementInput';
import FileUpload from '@/components/business/FileUpload';
import type { UploadFile } from '@/types/upload';
import SEO from '@/components/common/SEO';
import { getErrorMessage } from '@/utils/apiError';
import { t } from '@/utils/i18n';

const DRAFT_STORAGE_KEY = 'quick_case_draft';

interface CaseDraft {
  plaintiffStatement: string;
  defendantStatement: string;
  evidenceUrls: string[];
}

const QuickExperienceCreate = () => {
  const navigate = useNavigate();
  const { session, createSession, setSession } = useSessionStore();
  const { createQuickCase, isLoading } = useCaseStore();

  const [currentStep, setCurrentStep] = useState(0);
  const [plaintiffStatement, setPlaintiffStatement] = useState('');
  const [defendantStatement, setDefendantStatement] = useState('');
  const [evidenceFiles, setEvidenceFiles] = useState<UploadFile[]>([]);
  const [isGeneratingDefendant, setIsGeneratingDefendant] = useState(false);
  const [autoSaveStatus, setAutoSaveStatus] = useState<'saved' | 'saving' | null>(null);
  const [recoveredCase, setRecoveredCase] = useState<{ id: string; status: string } | null>(null);
  const [sessionInitError, setSessionInitError] = useState<string | null>(null);
  const [isRetryingSession, setIsRetryingSession] = useState(false);

  const submitLockRef = useRef(false);
  const mountedRef = useMountedRef();
  const autoGenTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const ensureSession = async (isManualRetry = false) => {
    if (isManualRetry && mountedRef.current) {
      setIsRetryingSession(true);
    }
    try {
      await createSession();
      if (mountedRef.current) setSessionInitError(null);
    } catch (error) {
      logger.warn('Failed to create session', error);
      if (mountedRef.current) setSessionInitError(t('quickCreate.sessionInitWeakWarning'));
    } finally {
      if (isManualRetry && mountedRef.current) setIsRetryingSession(false);
    }
  };

  useEffect(() => {
    const existingSessionId = sessionStorage.get() || session?.session_id;
    if (!existingSessionId) {
      createSession()
        .then(() => { if (mountedRef.current) setSessionInitError(null); })
        .catch((error: unknown) => {
          logger.warn('Failed to create session', error);
          if (mountedRef.current) setSessionInitError(t('quickCreate.sessionInitWeakWarning'));
        });
    }
  }, [session, createSession, mountedRef]);

  const sessionId = session?.session_id ?? sessionStorage.get();
  useEffect(() => {
    if (!sessionId) return;
    const checkRecoveredCase = async () => {
      try {
        const { getCaseBySessionId } = await import('@/services/api/case');
        const existingCase = await getCaseBySessionId(sessionId);
        if (existingCase && existingCase.status === 'draft' && mountedRef.current) {
          setRecoveredCase({ id: existingCase.id, status: existingCase.status });
        }
      } catch (error) {
        logger.warn('Failed to check recovered case', error);
      }
    };
    checkRecoveredCase();
  }, [sessionId]);

  useEffect(() => {
    const draft = localStore.get<CaseDraft>(DRAFT_STORAGE_KEY);
    if (draft) {
      setPlaintiffStatement(draft.plaintiffStatement || '');
      setDefendantStatement(draft.defendantStatement || '');
    }
  }, []);

  useEffect(() => {
    if (!plaintiffStatement && !defendantStatement) return;
    setAutoSaveStatus('saving');
    const timer = setTimeout(() => {
      localStore.set(DRAFT_STORAGE_KEY, { plaintiffStatement, defendantStatement, evidenceUrls: [] });
      if (mountedRef.current) {
        setAutoSaveStatus('saved');
        setTimeout(() => { if (mountedRef.current) setAutoSaveStatus(null); }, 2000);
      }
    }, 1000);
    return () => clearTimeout(timer);
  }, [plaintiffStatement, defendantStatement, mountedRef]);

  const canSubmit = validateStatement(plaintiffStatement).valid;

  const handleAutoGenerateDefendant = () => {
    if (!plaintiffStatement.trim()) {
      toast.info(t('message.fillPlaintiffFirst'));
      return;
    }
    setIsGeneratingDefendant(true);
    const source = plaintiffStatement.slice(0, 120);
    const draft = t('quickCreate.defendantDraftTemplate').replace('{source}', source);
    if (autoGenTimeoutRef.current) clearTimeout(autoGenTimeoutRef.current);
    autoGenTimeoutRef.current = setTimeout(() => {
      if (!mountedRef.current) return;
      setDefendantStatement(draft);
      setIsGeneratingDefendant(false);
      toast.success(t('message.defendantDraftDone'));
    }, 600);
  };

  useEffect(() => {
    return () => { if (autoGenTimeoutRef.current) clearTimeout(autoGenTimeoutRef.current); };
  }, []);

  const handleSubmit = async () => {
    if (submitLockRef.current) return;
    if (!canSubmit) {
      toast.warning(t('message.completePlaintiff'));
      return;
    }
    submitLockRef.current = true;
    try {
      if (!sessionStorage.get() && !session?.session_id) {
        await ensureSession();
      }
      const result = await createQuickCase({
        plaintiff_statement: plaintiffStatement.trim(),
        defendant_statement: defendantStatement.trim() || '',
        evidence_urls: [],
      });
      if (!result?.case?.id) throw new Error(t('message.submitFail'));

      if (result.session_id) {
        sessionStorage.set(result.session_id);
        caseSessionMap.set(result.case.id, result.session_id);
        if (result.session_expires_at) {
          setSession({ session_id: result.session_id, expires_at: result.session_expires_at });
        }
      }

      const filesToUpload = evidenceFiles
        .filter((f): f is UploadFile & { originFileObj: File } => Boolean(f?.originFileObj))
        .map((f) => f.originFileObj);

      if (filesToUpload.length > 0) {
        try {
          const { uploadEvidence } = await import('@/services/api/case');
          const sessionIdToUse = result.session_id || sessionStorage.get() || session?.session_id;
          if (sessionIdToUse) await uploadEvidence(result.case.id, filesToUpload as File[], sessionIdToUse);
        } catch {
          try { localStorage.setItem(`pending_evidence_${result.case.id}`, 'true'); } catch { /* noop */ }
        }
      }

      localStore.remove(DRAFT_STORAGE_KEY);
      if (mountedRef.current) navigate(`/quick-experience/result/${result.case.id}`);
    } catch (error: unknown) {
      if (mountedRef.current) toast.error(getErrorMessage(error, 'message.submitFail'));
    } finally {
      submitLockRef.current = false;
    }
  };

  const handleNextStep = () => {
    if (currentStep === 0 && !canSubmit) {
      toast.warning(t('message.completePlaintiff'));
      return;
    }
    setCurrentStep(prev => Math.min(prev + 1, 2));
  };

  const handlePrevStep = () => {
    setCurrentStep(prev => Math.max(prev - 1, 0));
  };

  return (
    <>
      <SEO title={t('quickCreate.title')} description={t('quickCreate.description')} keywords={t('quickCreate.keywords')} />

      <div className="flex min-h-screen flex-col bg-background">
        {/* Fixed Header */}
        <header className="fixed inset-x-0 top-0 z-50 flex items-center justify-between bg-background/90 px-6 py-5 backdrop-blur-xl">
          <button
            onClick={() => navigate('/')}
            className="font-semibold text-muted-foreground transition-colors hover:text-primary"
            aria-label={t('quickCreate.close')}
          >
            <X className="size-5" />
          </button>
          <div className="flex items-center gap-4">
            {autoSaveStatus === 'saving' && (
              <span className="text-sm text-muted-foreground animate-pulse">{t('quickCreate.autoSaving')}</span>
            )}
            {autoSaveStatus === 'saved' && (
              <span className="text-sm text-success">{t('quickCreate.autoSaved')}</span>
            )}
            <Progress value={((currentStep + 1) / 3) * 100} className="w-[200px] h-1.5" />
          </div>
        </header>

        {/* Recovered Case Banner */}
        {recoveredCase && (
          <div className="fixed left-1/2 top-20 z-50 w-full max-w-md -translate-x-1/2 px-4">
            <div className="flex items-center justify-between rounded-2xl border border-primary/20 bg-primary-light p-4 shadow-lg">
              <span className="text-sm font-medium text-foreground">{t('quickCreate.recoveredCase.title')}</span>
              <Button size="sm" onClick={() => navigate(`/quick-experience/result/${recoveredCase.id}`)}>
                {t('quickCreate.recoveredCase.continue')}
              </Button>
            </div>
          </div>
        )}

        {/* Session Init Warning */}
        {sessionInitError && (
          <div className="mx-auto mb-6 mt-20 w-full max-w-3xl px-4">
            <div className="flex items-start gap-3 rounded-2xl border border-warning/30 bg-warning/5 p-4">
              <AlertTriangle className="mt-0.5 size-5 shrink-0 text-warning" />
              <div className="flex-1">
                <p className="text-sm font-medium text-foreground">{sessionInitError}</p>
                <p className="mt-1 text-sm text-muted-foreground">{t('quickCreate.sessionInitWeakHint')}</p>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={() => void ensureSession(true)}
                disabled={isRetryingSession}
              >
                {isRetryingSession && <Loader2 className="size-3 animate-spin" />}
                {t('quickCreate.sessionInitRetry')}
              </Button>
            </div>
          </div>
        )}

        {/* Step Content */}
        <AnimatePresence mode="wait">
          {currentStep === 0 && (
            <motion.div
              key="step0"
              className="flex flex-1 items-center justify-center px-6 pt-24 pb-10"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
            >
              <div className="w-full max-w-[720px]">
                <h2 className="mb-4 text-[clamp(28px,4vw,40px)] font-extrabold leading-tight tracking-tight text-foreground font-heading">
                  {t('quickCreate.step1.title')}
                </h2>
                <p className="mb-8 text-lg text-muted-foreground">
                  {t('quickCreate.step1.subtitle')}
                </p>

                <StatementInput
                  value={plaintiffStatement}
                  onChange={setPlaintiffStatement}
                  role="plaintiff"
                  showGuide={true}
                  minLength={30}
                />

                <div className="mt-8 flex items-center gap-4">
                  <Button
                    size="lg"
                    onClick={handleNextStep}
                    disabled={!canSubmit}
                    className="h-14 rounded-full px-12 text-base font-semibold shadow-md transition-all hover:-translate-y-0.5 hover:shadow-lg"
                  >
                    {t('quickCreate.step.next')}
                  </Button>
                  <span className="text-sm text-muted-foreground">{t('quickCreate.step.enterHint')}</span>
                </div>
              </div>
            </motion.div>
          )}

          {currentStep === 1 && (
            <motion.div
              key="step1"
              className="flex flex-1 items-center justify-center px-6 pt-24 pb-10"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
            >
              <div className="w-full max-w-[720px]">
                {/* Handoff alert */}
                <div className="mb-8 flex items-start gap-3 rounded-2xl border border-primary/20 bg-primary-light/50 p-4">
                  <Info className="mt-0.5 size-5 shrink-0 text-primary" />
                  <p className="text-sm font-medium text-foreground">{t('quickCreate.step2.handoffPrompt')}</p>
                </div>

                <h2 className="mb-4 text-[clamp(28px,4vw,40px)] font-extrabold leading-tight tracking-tight text-foreground font-heading">
                  {t('quickCreate.step2.title')}
                </h2>
                <p className="mb-8 text-lg text-muted-foreground">
                  {t('quickCreate.step2.subtitle')}
                </p>

                <StatementInput
                  value={defendantStatement}
                  onChange={setDefendantStatement}
                  role="defendant"
                  showGuide={true}
                  allowEmpty
                  minLength={MIN_DEFENDANT_LENGTH}
                />

                <div className="mt-8 flex items-center gap-4">
                  <Button
                    variant="outline"
                    size="lg"
                    onClick={handlePrevStep}
                    className="h-14 rounded-full px-8 text-base font-semibold"
                  >
                    {t('quickCreate.step.prev')}
                  </Button>
                  <Button
                    size="lg"
                    onClick={handleNextStep}
                    className="h-14 rounded-full px-12 text-base font-semibold shadow-md transition-all hover:-translate-y-0.5 hover:shadow-lg"
                  >
                    {t('quickCreate.step.next')}
                  </Button>
                  <button
                    type="button"
                    onClick={handleAutoGenerateDefendant}
                    disabled={isGeneratingDefendant}
                    className="text-sm font-medium text-primary hover:text-primary-hover disabled:text-muted-foreground transition-colors flex items-center gap-1.5"
                  >
                    {isGeneratingDefendant && <Loader2 className="size-3 animate-spin" />}
                    {t('quickCreate.autoWrite')}
                  </button>
                </div>
              </div>
            </motion.div>
          )}

          {currentStep === 2 && (
            <motion.div
              key="step2"
              className="flex flex-1 items-center justify-center px-6 pt-24 pb-10"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
            >
              <div className="w-full max-w-[720px]">
                <h2 className="mb-4 text-[clamp(28px,4vw,40px)] font-extrabold leading-tight tracking-tight text-foreground font-heading">
                  {t('quickCreate.step3.title')}
                </h2>
                <p className="mb-8 text-lg text-muted-foreground">
                  {t('quickCreate.step3.subtitle')}
                </p>

                <div className="rounded-3xl border border-border bg-card p-8 shadow-sm">
                  <FileUpload value={evidenceFiles} onChange={setEvidenceFiles} maxCount={MAX_IMAGE_COUNT} />
                </div>

                <div className="mt-12 flex items-center gap-4">
                  <Button
                    variant="outline"
                    size="lg"
                    onClick={handlePrevStep}
                    className="h-14 rounded-full px-8 text-base font-semibold"
                  >
                    {t('quickCreate.step.prev')}
                  </Button>
                  <Button
                    size="lg"
                    onClick={handleSubmit}
                    disabled={isLoading}
                    className="h-14 rounded-full px-12 text-base font-semibold shadow-lg transition-all hover:-translate-y-0.5 hover:shadow-xl"
                  >
                    {isLoading ? (
                      <span className="flex items-center gap-2">
                        <Loader2 className="size-4 animate-spin" />
                        {t('quickCreate.submitting')}
                      </span>
                    ) : t('quickCreate.submitAndAnalyze')}
                  </Button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </>
  );
};

export default QuickExperienceCreate;
